# 七、异常和错误处理

## 异常和错误

由于多种原因，您的代码可能会出错。一个原因是程序员写了一些有错误的代码。错误、缺陷和 bug 是我们给程序代码中不太正确的部分贴上的标签。错误的发生是因为我们作为程序员并不完美。我们是人，总会犯一些错误。在你编程生涯的早期，你会发现一切都不是一帆风顺的。 <sup class="calibre4">1</sup>

有时，您可以控制程序的输入数据和行为，但是您的代码被处理成曲线球的方式之多，超出了您处理它们的能力。从这个挑战中诞生了一种叫做*防御性编程*的方法。 <sup class="calibre4">2</sup>

防御性编程不是一种胆怯的方法或平庸的态度。这是一门直面失败可能性的学科。这个规程的一个重要部分是错误和异常处理的有效实现。

让我们看一个例子。假设您有一些实现除法运算的代码，如下所示:

```py
quotient = a / b
```

可能会出什么问题？如果 b 的值为零，那么明显的问题就出现了。我们会看到什么？

```py
>>> quotient = 73 / 0.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
>>>
```

我们感兴趣的是文本 ZeroDivisionError:float division by zero。Python 解释器引发了一个错误 ZeroDivisionError，并提供了一条错误消息，尽管这条消息非常简洁。

如果这个代码片段在程序中间，程序就会失败并终止。如果我们想让程序处理错误并继续下一次计算，那对我们来说没什么用。我们使用术语*错误处理*或者更常见的是*异常处理*，来指代我们是如何做到这一点的。

Python 有许多内置的异常类型——ZeroDivisionError 只是其中之一——我们可以捕获这些事件，并在代码中处理它们。下面是一个示例程序 division.py:

```py
1   print('Input two numbers. the first will be divided by the second')
2   
3   afirst = input('first number:')
4   first=float(afirst)
5   asecond = input('second number:')
6   second = float(asecond)
7   
8   quotient = first / second
9   print('Quotient first/second = ',quotient)
```

如果你运行这个，输入 1 和 2，结果是 0.5，没问题。如果您输入 1 和 0，您将再次得到 ZeroDivisionError 消息。

这是这个程序的新版本，divisionHandled.py。

```py
1   print('Input two numbers. The first will be divided by the second')
2   
3   afirst = input('1st number:')
4   asecond = input('2nd number:')
5   
6   try:
7       first=float(afirst)
8       second = float(asecond)
9       quotient = first / second
10      print('Quotient 1st/2nd = ',quotient)
11  except Exception as diag:
12      print(diag.__class__.__name__,':',diag)
```

在本例中，我们在第 6 行的 try:子句中包含了一些代码(两个文本到浮点数的转换和除法)。如果 try:子句中的任何代码引发错误，它将被第 11 行的 except:子句捕获。

except:子句标识异常类型，并且可选地标识存储异常数据的变量。Exception 是错误类型的顶级类，因此它捕获所有错误。在 except 代码块中，代码打印诊断信息。__class__。__name__ 属性，用于命名错误类型。

目前为止，一切顺利。如果你玩这个程序，你可以尝试输入错误的数据，如下所示。

```py
D:\LeanPython\programs>python divisionHandled.py
Input two numbers. The first will be divided by the second
1st number:
2nd number:
ValueError : could not convert string to float:

D:\LeanPython\programs>python divisionHandled.py
Input two numbers. The first will be divided by the second
1st number:1
2nd number:0
ZeroDivisionError : float division by zero
```

第一次运行时，浮点转换代码失败。通过查看代码，我们知道这是第一次转换，但不知道代码的最终用户可能会感到困惑。因此，一般来说，建议:

*   我们处理特定的错误，而不是无所不包。

*   给每一段代码提供自己的异常处理程序来定位错误。

这是我们完全错误处理代码的最终版本:divisionHandledV2.py。

```py
1   print('Input two numbers. The first will be divided by the second')
2   
3   afirst = input('1st number:')
4   try:
5     first=float(afirst)
6     asecond = input('2nd number:')
7     try:
8       second = float(asecond)
9       try:
10        quotient = first / second
11        print('Quotient 1st/2nd = ',quotient)
12      except ZeroDivisionError as diag:
13        print(diag,': 2nd number must be non-zero')
14    except ValueError as diag:
15      print(diag,'2nd number')
16  except ValueError as diag:
17      print(diag,'1st number')
```

有点棘手的是，在测试之前很难知道会出现什么类型的错误，所以一般的方法可能是这样的:

*   首先，在您预期会发生异常的地方捕获所有异常。

*   其次，测试你能想到的所有异常，触发它们，并记下它们发生的位置。

*   对于您找到的每种异常类型，创建一个特定于该异常的异常子句。

顺便说一下，请注意，如果将多个异常类型放在一个 tuple 中，就有可能捕获它们；例如:

```py
except (ValueError, ZeroDivisionError) [as e]:
```

处理出现的错误的一个显而易见的替代方法是对输入数据的验证更加严格。在前面的例子中，这可能是一个更好的选择。但是，在某些情况下，无法提前检查异常，因为导致异常的数据值是中间计算的结果，可能不容易预测。

异常类型的范围很大。它们涵盖了类型转换、算术、文件 I/O、数据库访问、字典和列表元素违规等等。完整的清单见附录。

# 脚注

可以说，你不能通过把事情做对来学习。你只会从错误中吸取教训。你会犯很多错误；这不是问题所在。如果你不从中吸取教训，问题就来了。你可能会学到的一句口头禅是，“快速失败！”从失败中学习。

2 见【http://en.wikipedia.org/wiki/Defensive_programming】的。